name: dynamic_service_example
description: An example of the Dart based dynamic_service
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dynamic_service:
    path: ../
  shelf_cors_headers: ^0.1.2

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  functions_framework_builder: ^0.4.5
  test: ^1.21.0
  test_process: ^2.0.2
