version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/plugins/aws"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/plugins/gcp"
    schedule:
      interval: "weekly"
