name: 'client'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+26'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: 'flutter'
  flutter_svg: '^2.0.12'
  rest_client: '^2.4.0'

dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'

flutter:
  uses-material-design: true
