name: 'client'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+22'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: 'flutter'
  flutter_svg: '^2.0.7'
  rest_client: '^2.2.2+2'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.1'

flutter: 
  uses-material-design: true
