name: 'client'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+9'

environment: 
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: 'flutter'
  flutter_svg: '^1.1.6'
  rest_client: '^2.2.1+1'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.1'

flutter: 
  uses-material-design: true
