name: dynamic_service
description: A Dart based service for handling dynamic requests and responses
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.1
  encrypt: ^5.0.1
  functions_framework: ^0.4.1
  http: ^0.13.4
  intl: ^0.17.0
  jose: ^0.3.2
  json_class: ^2.1.2+4
  json_path: ^0.4.0
  latlong2: ^0.8.1
  logging: ^1.0.2
  meta: ^1.7.0
  mime: ^1.0.1
  rest_client: ^2.1.1
  shelf: ^1.3.0
  template_expressions: ^1.1.3
  uuid: ^3.0.6
  yaon: ^1.0.0

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  functions_framework_builder: ^0.4.5
  test: ^1.20.1
  test_process: ^2.0.2
