name: dynamic_service
description: A Dart based service for handling dynamic requests and responses
homepage: https://github.com/peiffer-innovations/dynamic_service
version: 0.9.1+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  crypto: ^3.0.1
  encrypt: ^5.0.1
  http: ^0.13.4
  intl: ^0.17.0
  jose: ^0.3.2
  json_class: ^2.1.2+4
  json_path: ^0.4.0
  json_schema2: ^2.0.2
  latlong2: ^0.8.1
  logging: ^1.0.1
  meta: ^1.7.0
  mime: ^1.0.1
  rest_client: ^2.1.3
  shelf: ^1.3.0
  template_expressions: ^1.1.7
  uuid: ^3.0.6
  yaon: ^1.0.1

dev_dependencies:
  args: ^2.3.1
  build_runner: ^2.1.7
  dependency_validator: ^3.1.2
  test: ^1.21.1
  test_process: ^2.0.2

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
