name: 'dynamic_service'
description: 'A Dart based service for handling dynamic requests and responses'
homepage: 'https://github.com/peiffer-innovations/dynamic_service'
version: '1.0.2+7'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: '^1.16.0'
  crypto: '^3.0.1'
  encrypt: '^5.0.1'
  http: '^0.13.6'
  intl: '^0.18.1'
  jose: '^0.3.3'
  json_class: '^2.2.1+3'
  json_path: '^0.5.2'
  json_schema2: '^5.1.2+2'
  latlong2: '^0.8.1'
  logging: '^1.1.1'
  meta: '^1.9.1'
  mime: '^1.0.4'
  rest_client: '^2.2.1+11'
  shelf: '^1.4.1'
  template_expressions: '^3.0.2+1'
  uuid: '^3.0.7'
  x509: '^0.2.3'
  yaon: '^1.1.1'

dev_dependencies:
  args: '^2.4.1'
  dependency_validator: '^3.2.2'
  flutter_lints: '^2.0.1'
  test: '^1.24.2'
  test_process: '^2.0.3'

false_secrets:
  - 'example/server/assets/keys/privateKey.pem'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
