services:
  - id: health-check
    criteria:
      method: GET
      path: /health-check
    steps:
      - type: set_response
        with:
          status: 204

  - id: hello
    criteria:
      method: GET
      path: /hello
    steps:
      - type: set_response
        with:
          body: "Hello World!"
          content-type: text/plain

  - id: goodbye
    criteria:
      method: GET
      path: /goodbye
    steps:
      - type: set_response
        with:
          body: "Goodbye Cruel World!!!"
          content-type: text/plain

  - id: get_greeting_regex
    criteria:
      method: GET
      path: /greeting/regex/(?<firstName>[^/]*)/(?<lastName>[^/]*)
    steps:
      - type: set_response
        with:
          body: "Hi ${path['firstName']} ${path['lastName']}"
          content-type: text/plain

  - id: get_greeting_simple
    criteria:
      method: GET
      path: /greeting/simple/:firstName/:lastName
    steps:
      - type: set_response
        with:
          body: "Hello ${path['firstName']} ${path['lastName']}"
          content-type: text/plain

  - id: timestamp
    criteria:
      path: /now
    steps:
      - type: set_response
        with:
          $ref: assets://body/now.json

  - id: name_generator_network
    criteria:
      path: /generate-name/network
    steps:
      - $ref: assets://steps/random_names.yaml
      - type: set_response
        with:
          $ref: https://peiffer-innovations.github.io/dynamic_service/pages/response.json

  - id: name_generator_network_yaml
    criteria:
      path: /generate-name/network/yaml
    steps:
      - $ref: assets://steps/random_names.yaml
      - type: set_response
        with:
          $ref: https://peiffer-innovations.github.io/dynamic_service/pages/response.yaml

  - id: name_generator_local
    criteria:
      path: /generate-name/local
    steps:
      - $ref: assets://steps/random_names.yaml
      - type: set_response
        with:
          $ref: assets://body/response.json

  - id: weather
    criteria:
      path: /weather
    steps:
      - type: set_response
        with:
          content-type: image/svg+xml
          $ref: assets://images/weatherchart.svg

  - id: mountain
    criteria:
      path: /mountain
    steps:
      - type: set_response
        with:
          content-type: image/jpeg
          $ref: assets://images/mountain.jpg

  - id: mountain_network
    criteria:
      path: /mountain/network
    steps:
      - type: set_response
        with:
          content-type: image/jpeg
          $ref: https://peiffer-innovations.github.io/dynamic_service/pages/mountain.jpg

  - id: for_each_array
    criteria:
      method: post
      path: /for_each/array
    steps:
      - type: set_variables
        with:
          array:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
          message: ""
      - type: for_each
        with:
          input: ${array}
          steps:
            - type: delay
              with:
                min: 100
                max: 300
            - type: set_variables
              with:
                message: |
                  ${message + index.toString() + ': ' + variable.toString() + ': ' + request['body']}

      - type: set_response
        with:
          content-type: text/plain
          body: ${message}

  - id: for_each_array_parallel
    criteria:
      method: post
      path: /for_each/array/parallel
    steps:
      - type: set_variables
        with:
          array:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
          message: ""
      - type: for_each
        with:
          input: ${array}
          parallel: true
          steps:
            - type: delay
              with:
                min: 100
                max: 300
            - type: set_variables
              with:
                message: |
                  ${message + index.toString() + ': ' + variable.toString() + ': ' + request['body']}

      - type: set_response
        with:
          content-type: text/plain
          body: ${message}

  - $ref: assets://services/greetings.yaml
  - $ref: assets://services/jwt.yaml
  - $ref: assets://services/users.yaml
