services:
  - id: hello
    criteria:
      method: GET
      path: /hello
    steps:
      - type: set_response
        with:
          body: "Hello World!"
          content-type: text/plain

  - id: goodbye
    criteria:
      method: GET
      path: /goodbye
    steps:
      - type: set_response
        with:
          body: "Goodbye Cruel World!!!"
          content-type: text/plain

  - id: get_greeting_regex
    criteria:
      method: GET
      path: /greeting/regex/(?<firstName>[^/]*)/(?<lastName>[^/]*)
    steps:
      - type: set_response
        with:
          body: "Hi ${path['firstName']} ${path['lastName']}"
          content-type: text/plain

  - id: get_greeting_simple
    criteria:
      method: GET
      path: /greeting/simple/:firstName/:lastName
    steps:
      - type: set_response
        with:
          body: "Hello ${path['firstName']} ${path['lastName']}"
          content-type: text/plain

  - id: timestamp
    criteria:
      path: /now
    steps:
      - type: set_response
        with:
          $ref: assets://body/now.json

  - id: name_generator
    criteria:
      path: /generate-name
    steps:
      - type: load_network
        with:
          requests:
            - id: firstName
              url: https://peiffer-innovations.github.io/dynamic_service/pages/first_names.json
            - id: lastName
              url: https://peiffer-innovations.github.io/dynamic_service/pages/last_names.json
      - type: shuffle_list
        with:
          list: ${json_path(load_network, '$.first.body.names')}
          variable: first
      - type: shuffle_list
        with:
          list: ${json_path(load_network, '$.last.body.names')}
          variable: last
      - type: set_variables
        with:
          first: ${json_path(load_network, '$.last.body.names').first}
          last: ${json_path(load_network, '$.last.body.names').first}
      - type: set_response
        with:
          $ref: https://peiffer-innovations.github.io/dynamic_service/pages/response.json

  - $ref: assets://services/greetings.yaml
  - $ref: assets://services/users.yaml
