name: 'dynamic_service_example'
description: 'An example of the Dart based dynamic_service'
version: '1.0.0+7'
publish_to: 'none'

environment: 
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  args: '^2.4.0'
  dynamic_service: 
    path: '../../'
  shelf_cors_headers: '^0.1.4'

dev_dependencies: 
  build_runner: '^2.3.3'
  dependency_validator: '^3.2.2'
  functions_framework_builder: '^0.4.7'
  test: '^1.24.1'
  test_process: '^2.0.3'
