name: 'dynamic_service_example'
description: 'An example of the Dart based dynamic_service'
version: '1.0.0+10'
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: '^2.4.1'
  dynamic_service:
    path: '../../'
  shelf_cors_headers: '^0.1.5'

dev_dependencies:
  build_runner: '^2.4.4'
  dependency_validator: '^3.2.2'
  functions_framework_builder: '^0.4.7'
  test: '^1.24.2'
  test_process: '^2.0.3'
