name: Pages Deployer

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/pages.yml
      - pages/**

jobs:
  publish:
    needs: build_number
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: source

      - uses: actions/checkout@v3
        with:
          path: pages
          ref: gh-pages

      - name: Setup Git
        shell: bash
        run: |
          set -e

          git config --global user.email "noop@github.com"
          git config --global user.name "action"
          git config --global url."https://action:${{ inputs.token }}@github.com/".insteadOf https://github.com/

      - name: Deploy pages
        run: |
          set +e
          rm -rf pages/pages

          set -e

          mkdir pages/pages
          cp -R source/pages/* pages/pages

          cd pages
          git add .
          git commit -m "[actions skip]: update pages"
          git push
