name: Dart Publisher

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/publisher.yml
      - pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1
        with:
          flutter_package: false

      - name: Publish
        uses: peiffer-innovations/actions-pub-publish@v1.0.1
        with:
          credentials: ${{ secrets.CREDENTIAL_JSON }}

      - uses: peiffer-innovations/actions-dart-version-autotag@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
